spring:
  config:
    import: optional:application-secrets.yaml
  application:
    name: E-commerce-Mini
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile


  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_mini?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: ${JWT_SIGNER_KEY}

app:
  oauth2:
    redirect-uri: http://localhost:5173/oauth2/redirect

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

